name: broshop_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  shared_preferences: 2.0.15
  google_sign_in: 5.4.2
  firebase_core: 2.4.1
  firebase_auth: 4.2.5
  flutter_signin_button: 2.0.0
  result_type: 0.2.0
  razorpay_flutter: ^1.3.4
  location: ^4.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true
  fonts: 
    - family: RobotoRegular
      fonts: 
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoBold
      fonts: 
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoMedium
      fonts: 
        - asset: assets/fonts/Roboto-Medium.ttf
