version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: broshop_test
      POSTGRES_PASSWORD: admin
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: